# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:1296262867@tcp(127.0.0.1:3306)/did"
        tables: "user,shares"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
